plugins {
	id 'java'
	id 'war'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

bootWar {
	archiveBaseName = 'gmarket'
	archiveFileName = 'ROOT.war'
	archiveVersion = "0.0.1"
}

bootWar.enabled = true 	// 단독으로 실행 가능
war.enabled = false		// 외장 톰캣을 사용


dependencies {
	// implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'	
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'
	
	// mybatis
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
	
	// HikariCP
	implementation 'com.zaxxer:HikariCP:5.0.1'
	
	// mariadb
	// implementation 'org.mariadb.jdbc:mariadb-java-client:3.1.4'
	
	// mssql
	implementation 'com.microsoft.sqlserver:mssql-jdbc:10.2.3.jre17'
	
	// sql log
	implementation 'org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1:1.16'
	
	// security 
	implementation 'org.springframework.boot:spring-boot-starter-security:3.3.4'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
	
	// jwt
	// implementation("io.jsonwebtoken:jjwt:0.12.6")
	
	// lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	
	// jackson
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.0'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.14.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.14.0'
	
	// developmentOnly 'org.springframework.boot:spring-boot-devtools'
	
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	// tomcat
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	
	// XSS Filter
	implementation("com.navercorp.lucy:lucy-xss-servlet:2.0.1")
	implementation("org.apache.commons:commons-text:1.13.1")
	
	// validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	
	// excel
	implementation 'org.apache.poi:poi-ooxml:5.2.5'
	
	// FTP 
	implementation("commons-net:commons-net:3.12.0")
}

tasks.named('test') {
	useJUnitPlatform()
}
