server:
  port: 8080

spring:
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false #개발 시에는 false
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://10.1.75.103:3306/reseller
      username: reseller
      password: dnvreseller
      driver-class-name: org.mariadb.jdbc.Driver
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      pool-name: HikariCP

logging:
  level:
    root: info

jwt:
  secret: HfjyZ8xMqo4tIiF6+gA0s37DEmG0ZxAhWdZUhqKsSg4=