
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false #개발 시에는 false
  datasource:
    gmarket:
      hikari:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:sqlserver://;serverName=192.168.0.122\SQLEXPRESS;databaseName=msdbgm;encrypt=true # encrypt=false 운영 환경에서는 true
        username: gmarket
        password: gmarket12#$
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        connection-timeout: 30000
        pool-name: HikariCP-GM
    auction:
      hikari:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:sqlserver://;serverName=192.168.0.122\SQLEXPRESS;databaseName=msdbau;encrypt=true # encrypt=false 운영 환경에서는 true
        username: gmarket
        password: gmarket12#$
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        connection-timeout: 30000
        pool-name: HikariCP-AU
logging:
  level:
    root: info

jwt:
  secret: HfjyZ8xMqo4tIiF6+gA0s37DEmG0ZxAhWdZUhqKsSg4=